### ISSUE TITLE
Error: Cannot find module 'import-global'

### ISSUE THREAD

**Issue by kvark** [christianvoigt/argdown#179]
See full log at https://github.com/kvark/webgpu-debate/runs/951839143
```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'import-global'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/hostedtoolcache/node/10.22.0/x64/lib/node_modules/@argdown/cli/dist/tryToInstallImageExport.js:26:41)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by christianvoigt** [comment]
Thanks for the report. Somehow I installed `import-global` only as devDependency so my local tests passed, but the built version on npm is missing the package. Sorry for that, I fixed it and published v1.5.1.
