### ISSUE TITLE
Argdown core, Test failing on Windows

### ISSUE THREAD

**Issue by cwkit** [christianvoigt/argdown#60]
√ can lex escaped chars
    1) can save correct token location data

  24 passing (300ms)
  1 failing

  1) Lexer
       can save correct token location data:

      AssertionError: expected 3 to equal 2
      + expected - actual

      -3
      +2

      at expectTokenLocation (D:\Code-Projekte\argdown\packages\argdown-core\test\lexer.spec.ts:22:32)
      at Context.<anonymous> (D:\Code-Projekte\argdown\packages\argdown-core\test\lexer.spec.ts:374:5)

**Comment by christianvoigt** [comment]
fixed in 1.0.0 (no auto-closing because of rebased monorepo branch).
