### ISSUE TITLE
Argdown-Core Test failing on Windows

### ISSUE THREAD

**Issue by cwkit** [christianvoigt/argdown#67]
Error Text: 

```
1) HtmlExport
       can export Argdown:

      AssertionError: expected '<!doctype html><html lang="en"><head><meta charset="utf8"><title>Title</title><link rel="stylesheet" href="./argdown.css"></head><body><div class="argdown"><h1 data-line="1" id="heading-title" class="has-line heading">Title</h1><div data-line="3" class="statement has-line"><span id="statement-statement" class="definition statement-definition definiendum">[<span class="title statement-title">Statement</span>]: </span>Hello World!<div class="relations"><div data-line="4" class="has-line outgoing support relation"><div class="outgoing support relation-symbol"><span>+</span></div><a href="#argument-argument" data-line="4" class="has-line reference argument-reference">&lt;<span class="title argument-title">Argument</span>&gt; </a></div></div></div><span id="argument-argument" class="definition argument-definition definiendum">&lt;<span class="title argument-title">Argument</span>&gt;: </span>Description 1 &lt; 2</div></body></html>' to equal '<!doctype html><html lang="en"><head><meta charset="utf8"><title>Title</title><link rel="stylesheet" href="./argdown.css"></head><body><div class="argdown"><h1 data-line="1" id="heading-title" class="has-line heading">Title</h1><div data-line="3" class="statement has-line"><span id="statement-statement" class="definition statement-definition definiendum">[<span class="title statement-title">Statement</span>]: </span>Hello World!<div class="relations"><div data-line="4" class="has-line outgoing support relation"><div class="outgoing support relation-symbol"><span>+</span></div><div data-line="4" class="argument has-line"></div></div></div></div><div data-line="6" class="argument has-line"><span id="argument-argument" class="definition argument-definition definiendum">&lt;<span class="title argument-title">Argument</span>&gt;: </span>Description 1 &lt; 2</div></div></body></html>'
      + expected - actual

      -<!doctype html><html lang="en"><head><meta charset="utf8"><title>Title</title><link rel="stylesheet" href="./argdown.css"></head><body><div class="argdown"><h1 data-line="1" id="heading-title" class="has-line heading">Title</h1><div data-line="3" class="statement has-line"><span id="statement-statement" class="definition
statement-definition definiendum">[<span class="title statement-title">Statement</span>]: </span>Hello World!<div class="relations"><div data-line="4" class="has-line outgoing support relation"><div class="outgoing support relation-symbol"><span>+</span></div><a href="#argument-argument" data-line="4" class="has-line reference argument-reference">&lt;<span class="title argument-title">Argument</span>&gt; </a></div></div></div><span id="argument-argument" class="definition argument-definition definiendum">&lt;<span class="title argument-title">Argument</span>&gt;: </span>Description 1 &lt; 2</div></body></html>
      +<!doctype html><html lang="en"><head><meta charset="utf8"><title>Title</title><link rel="stylesheet" href="./argdown.css"></head><body><div class="argdown"><h1 data-line="1" id="heading-title" class="has-line heading">Title</h1><div data-line="3" class="statement has-line"><span id="statement-statement" class="definition
statement-definition definiendum">[<span class="title statement-title">Statement</span>]: </span>Hello World!<div class="relations"><div data-line="4" class="has-line outgoing support relation"><div class="outgoing support relation-symbol"><span>+</span></div><div data-line="4" class="argument has-line"></div></div></div></div><div data-line="6" class="argument has-line"><span id="argument-argument" class="definition argument-definition definiendum">&lt;<span class="title argument-title">Argument</span>&gt;: </span>Description 1 &lt; 2</div></div></body></html>

      at Context.<anonymous> (D:\Code-Projekte\argdown\packages\argdown-core\test\HtmlExportPlugin.spec.ts:23:28)
      at callFn (D:\Code-Projekte\argdown\packages\argdown-core\node_modules\mocha\lib\runnable.js:372:21)
      at Test.Runnable.run (D:\Code-Projekte\argdown\packages\argdown-core\node_modules\mocha\lib\runnable.js:364:7)
      at Runner.runTest (D:\Code-Projekte\argdown\packages\argdown-core\node_modules\mocha\lib\runner.js:455:10)
      at D:\Code-Projekte\argdown\packages\argdown-core\node_modules\mocha\lib\runner.js:573:12
      at next (D:\Code-Projekte\argdown\packages\argdown-core\node_modules\mocha\lib\runner.js:369:14)
      at D:\Code-Projekte\argdown\packages\argdown-core\node_modules\mocha\lib\runner.js:379:7
      at next (D:\Code-Projekte\argdown\packages\argdown-core\node_modules\mocha\lib\runner.js:303:14)
      at Immediate.<anonymous> (D:\Code-Projekte\argdown\packages\argdown-core\node_modules\mocha\lib\runner.js:347:5)
      at runCallback (timers.js:810:20)
      at tryOnImmediate (timers.js:768:5)
      at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by christianvoigt** [comment]
fixed in 1.0.0 (no auto-closing because of rebased monorepo branch).
