### ISSUE TITLE
undercut not working in vscode (/ language server)

### ISSUE THREAD

**Issue by TimSoethout** [christianvoigt/argdown#96]
HI, I'm using this example in vscode using the plugin from the vscode extensions:

```argdown
[Main]
 + Supporting
 <_ abc
```

With the last line the rendering does not update does not work.
This syntax does seem to support it by displaying purple.

Error message in the console:
```
[ArgdownApplication]: Processor build-model canceled.
[build-model/ModelPlugin]: Error: Missing inference.
    at ArgdownTreeWalker.outgoingUndercutEntry (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/core/dist/src/plugins/ModelPlugin.js:820:31)
    at ArgdownTreeWalker.emit (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/eventemitter3/index.js:192:18)
    at ArgdownTreeWalker.visitNode (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/core/dist/src/ArgdownTreeWalker.js:11:26)
    at ArgdownTreeWalker.visitNode (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/core/dist/src/ArgdownTreeWalker.js:15:34)
    at ArgdownTreeWalker.visitNode (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/core/dist/src/ArgdownTreeWalker.js:15:34)
    at ArgdownTreeWalker.visitNode (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/core/dist/src/ArgdownTreeWalker.js:15:34)
    at ArgdownTreeWalker.walk (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/core/dist/src/ArgdownTreeWalker.js:28:18)
    at AsyncArgdownApplication.runAsync (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/node/dist/src/AsyncArgdownApplication.js:200:38)
    at processTextForProviders (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/language-server/dist/src/server.js:167:33)
    at processDocForProviders (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/language-server/dist/src/server.js:157:22)
[ArgdownApplication]: Processor build-model canceled.
[build-model/ModelPlugin]: Error: Missing inference.
    at ArgdownTreeWalker.outgoingUndercutEntry (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/core/dist/src/plugins/ModelPlugin.js:820:31)
    at ArgdownTreeWalker.emit (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/eventemitter3/index.js:192:18)
    at ArgdownTreeWalker.visitNode (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/core/dist/src/ArgdownTreeWalker.js:11:26)
    at ArgdownTreeWalker.visitNode (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/core/dist/src/ArgdownTreeWalker.js:15:34)
    at ArgdownTreeWalker.visitNode (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/core/dist/src/ArgdownTreeWalker.js:15:34)
    at ArgdownTreeWalker.visitNode (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/core/dist/src/ArgdownTreeWalker.js:15:34)
    at ArgdownTreeWalker.walk (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/core/dist/src/ArgdownTreeWalker.js:28:18)
    at AsyncArgdownApplication.run (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/core/dist/src/ArgdownApplication.js:172:38)
    at validateTextDocument (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/language-server/dist/src/server.js:125:33)
    at documents.onDidChangeContent.change (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/language-server/dist/src/server.js:121:5)
[ArgdownApplication]: Processor build-model canceled.
[build-model/ModelPlugin]: Error: Missing inference.
    at ArgdownTreeWalker.outgoingUndercutEntry (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/core/dist/src/plugins/ModelPlugin.js:820:31)
    at ArgdownTreeWalker.emit (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/eventemitter3/index.js:192:18)
    at ArgdownTreeWalker.visitNode (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/core/dist/src/ArgdownTreeWalker.js:11:26)
    at ArgdownTreeWalker.visitNode (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/core/dist/src/ArgdownTreeWalker.js:15:34)
    at ArgdownTreeWalker.visitNode (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/core/dist/src/ArgdownTreeWalker.js:15:34)
    at ArgdownTreeWalker.visitNode (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/core/dist/src/ArgdownTreeWalker.js:15:34)
    at ArgdownTreeWalker.walk (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/core/dist/src/ArgdownTreeWalker.js:28:18)
    at AsyncArgdownApplication.runAsync (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/node/dist/src/AsyncArgdownApplication.js:200:38)
    at connection.onFoldingRanges (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/language-server/dist/src/server.js:256:47)
    at handleRequest (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/vscode-jsonrpc/lib/main.js:367:27)
[ArgdownApplication]: Processor build-model canceled.
[build-model/ModelPlugin]: Error: Missing inference.
    at ArgdownTreeWalker.outgoingUndercutEntry (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/core/dist/src/plugins/ModelPlugin.js:820:31)
    at ArgdownTreeWalker.emit (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/eventemitter3/index.js:192:18)
    at ArgdownTreeWalker.visitNode (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/core/dist/src/ArgdownTreeWalker.js:11:26)
    at ArgdownTreeWalker.visitNode (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/core/dist/src/ArgdownTreeWalker.js:15:34)
    at ArgdownTreeWalker.visitNode (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/core/dist/src/ArgdownTreeWalker.js:15:34)
    at ArgdownTreeWalker.visitNode (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/core/dist/src/ArgdownTreeWalker.js:15:34)
    at ArgdownTreeWalker.walk (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/core/dist/src/ArgdownTreeWalker.js:28:18)
    at AsyncArgdownApplication.runAsync (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/node/dist/src/AsyncArgdownApplication.js:200:38)
    at connection.onDocumentSymbol (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/@argdown/language-server/dist/src/server.js:242:47)
    at handleRequest (/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/vscode-jsonrpc/lib/main.js:367:27)

```

**Comment by christianvoigt** [comment]
Good find, this is a bug. 

Originally I only allowed undercuts for argument elements (if there is no inference, there is nothing to undercut). But as it should be possible to use Argdown without distinguishing between arguments and statements, I added undercuts for statements as well. But apparently the parser is still looking for an inference... 

For now, please use undercuts only with arguments. This should work:

```argdown
<Main>
  + Supporting
  <_ abc
```

**Comment by TimSoethout** [comment]
Maybe you can allow undercuts in the loose mode? And for strict it really needs to undercut a premise.

**Comment by sbrugman** [comment]
There is a related issue, probably caused by the same bug. Undercuts are not working without explicitly stating the relation direction, even with arguments. For example, this does not work:
```
<Main>
  + Supporting
  _ abc
```

While this works perfectly fine:
```
<Main>
  + Supporting
  <_ abc
```

**Comment by christianvoigt** [comment]
Hi @sbrugman. Thanks for pointing that out. I think at first I only wanted to allow `<_` and `_>` because I feared that `_` and `-` are visually too difficult to distinguish. I then forgot about that and wrote the documentation saying that `_` is also allowed. So I should update the parser and add support for `_`, because it is more in line with the rest of the syntax.

I will open a new issue for this, because it is unrelated to the older bug.
